---
layout: default
title:  "Coffee production"
date:   2015-10-08 15:46:20
categories: pocketbook
---

```{r setup-code-part6}
knitr::read_chunk(paste0(root.dir,"input/code/code_part6.R"))
```


```{r part6_setup, eval=include_part6}
```


```{r P6coffeeprodTEXT, eval=P6coffeeprod, short_text_ChartPage=P6coffeeprod}
```


```{r P6coffeeprodData, cache=TRUE,results='hide', eval=P6coffeeprod}
```



```{r P6coffeeprodTOPRIGHT, eval=P6coffeeprod, top_right_plot=P6coffeeprod, fig.height=top_right_plot_height, fig.width=top_right_plot_width}
```


```{r P6coffeeprodLEFT, eval=P6coffeeprod, left_plot=P6coffeeprod, fig.height=left_plot_height, fig.width=left_plot_width}
```

```{r P6coffeeprodRIGHT, eval=P6coffeeprod ,right_plot=P6coffeeprod, fig.height=right_plot_height, fig.width=right_plot_width}
```


```{r P6coffeeprodBOTTOM, eval=P6coffeeprod, bottom_plot=P6coffeeprod, fig.height=bottom_plot_height, fig.width=bottom_plot_width}
```


```{r P6coffeeprodMAP, eval=P6coffeeprod, map_plot=P6coffeeprod, fig.width=map_plot_width, fig.height= map_plot_height}
```
