---
layout: default
title:  "Coffee prices"
date:   2015-10-08 15:46:20
categories: pocketbook
---


```{r setup-code-part6}
knitr::read_chunk(paste0(root.dir,"input/code/code_part6.R"))
```


```{r part6_setup, eval=include_part6}
```

```{r P6coffeepricesTEXT, eval=P6coffeeprices, short_text_ChartPage=P6coffeeprices}
```


```{r P6coffeepricesData, cache=TRUE,results='hide', eval=P6coffeeprices}
```



```{r P6coffeepricesTOPRIGHT, eval=P6coffeeprices, top_right_plot=P6coffeeprices, fig.height=top_right_plot_height, fig.width=top_right_plot_width}
```


```{r P6coffeepricesLEFT, eval=P6coffeeprices, left_plot=P6coffeeprices, fig.height=left_plot_height, fig.width=left_plot_width}
```

```{r P6coffeepricesRIGHT, eval=P6coffeeprices ,right_plot=P6coffeeprices, fig.height=right_plot_height, fig.width=right_plot_width}
```


```{r P6coffeepricesBOTTOM, eval=P6coffeeprices, bottom_plot=P6coffeeprices, fig.height=bottom_plot_height, fig.width=bottom_plot_width}
```


```{r P6coffeepricesMAP, eval=P6coffeeprices, map_plot=P6coffeeprices, fig.width=map_plot_width, fig.height= map_plot_height}
```

