---
layout: default
title:  "Overview"
date:   2015-10-08 15:46:20
categories: pocketbook
---



```{r setup-code-part5}
knitr::read_chunk(paste0(root.dir,"input/code/code_part5.R"))
```


```{r part5_setup, eval=include_part5}
```

<!--
#    ___                                  _                   
#   / _ \  __   __   ___   _ __  __   __ (_)   ___  __      __
#  | | | | \ \ / /  / _ \ | '__| \ \ / / | |  / _ \ \ \ /\ / /
#  | |_| |  \ V /  |  __/ | |     \ V /  | | |  __/  \ V  V / 
#   \___/    \_/    \___| |_|      \_/   |_|  \___|   \_/\_/  
#                                                            
-->


```{r P5overTEXT, eval=P5over, short_text_ChartPage=P5over}
```


```{r P5overData, results='hide', eval=P5over}
```


```{r P5overTOPRIGHT, eval=P5over, top_right_plot=P5over, fig.height=top_right_plot_height, fig.width=top_right_plot_width}
```


```{r P5overLEFT, eval=P5over, left_plot=P5over, fig.height=left_plot_height, fig.width=left_plot_width}
```

```{r P5overRIGHT, eval=P5over, right_plot=P5over, fig.height=left_plot_height, fig.width=left_plot_width}
```


```{r P5overBOTTOM, eval=P5over, bottom_plot=P5over, fig.height=bottom_plot_height, fig.width=bottom_plot_width}
```


```{r P5overMAP, eval=P5over, map_plot=P5over, fig.height=map_plot_height, fig.width=map_plot_width}
```



[jekyll-gh]: https://github.com/jekyll/jekyll
[jekyll]:    http://jekyllrb.com
